### PR TITLE
localhost:8085 => wiki.jenkins.io

### PR DESCRIPTION
**Pull request by halkeye**

### CODE REVIEW

**Comment by halkeye** [comment]
see https://plugins.jenkins.io/github-branch-source/ as it has a dead link to localhost:8085

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
Can someone add the infra team as admin here?

**Comment by halkeye** [comment]
I can merge, but I'm not an admin

**Comment by timja** [comment]
@dduportal

**Pull request merged**
