### PR TITLE
ReadMe changes for qmetry-test-management

### PR DESCRIPTION
**Pull request by QMetryDev**

### CODE REVIEW

**Review by halkeye — CHANGES_REQUESTED** [review]
This repo is for legacy documentation. You should be updating the real repo's docs

https://github.com/jenkinsci/qmetry-test-management-plugin/blob/master/pom.xml#L20 should get changed to either `https://github.com/jenkinsci/qmetry-test-management-plugin` or point to a specific file (ex https://github.com/jenkinsci/qmetry-test-management-plugin/blob/master/README.md i believe)

You'll need to do a release to update <url> but after that you can update docs on demand.

**Comment by MarkEWaite** [comment]
Refer to the detailed instructions at https://www.jenkins.io/doc/developer/publishing/wiki-page/#migrating-from-wiki-to-github

See the videos that are embedded at https://www.jenkins.io/participate/document/ if you prefer video presentations rather than text.

**Comment by daniel-beck** [comment]
We no longer have a request to migrate wiki content on the plugin site. Perhaps it makes sense to restore that?

**Comment by halkeye** [comment]
> We no longer have a request to migrate wiki content on the plugin site. Perhaps it makes sense to restore that?

Its a bug, the url is raw.githubusercontent.com/jenkins-infra/plugins-wiki-doc but the [code](https://github.com/jenkins-infra/plugin-site/blob/master/plugins/plugin-site/src/templates/plugin.jsx#L23 is checking for "github.com/jenkins-infra/plugins-wiki-docs")

**Comment by halkeye** [comment]
image

**Pull request closed without merging**
